import TenantShell from "@/components/layout/TenantShell";
import ContentContainer from "@/components/layout/ContentContainer";
import { APP_BACKGROUND_COLOR } from "@/constants/theme";
import { getTenantAppConfig } from "@/lib/get-tenant-app-config";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config = await getTenantAppConfig();

  const bodyStyle: React.CSSProperties = {
    backgroundColor: APP_BACKGROUND_COLOR,
    ...(config
      ? { ["--tenant-primary" as string]: config.branding.primaryColor }
      : {}),
  };

  return (
    <html
      lang="fr"
      className={`${manrope.variable} h-full font-sans antialiased`}
    >
      <body className="flex min-h-full flex-col font-sans" style={bodyStyle}>
        {config ? (
          <TenantShell
            tenantId={config.tenantId}
            slug={config.slug}
            branding={config.branding}
            name={config.name}
            currency={config.currency}
            features={config.features}
            payoutMode={config.payoutMode ?? null}
            escrowEnabled={config.escrowEnabled ?? false}
            stripePublishableKey={config.stripePublishableKey}
            mapboxPublicToken={config.mapboxPublicToken}
            privacyPolicyUrl={config.privacyPolicyUrl}
            cgvUrl={config.cgvUrl}
            supportEmail={config.supportEmail}
          >
            {children}
          </TenantShell>
        ) : (
          <ContentContainer className="flex min-h-full flex-1 flex-col">
            {children}
          </ContentContainer>
        )}
      </body>
    </html>
  );
}
